apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-native-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: cloudnative.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloud-native-app-svc
                port:
                  number: 80
